PLAYERS_FILE = "players.csv"
PLAYERS_AMOUNT = 500
MIN_YEAR_BIRTH = 1985
MAX_YEAR_BIRTH = 2005
MIN_MMR = 5000
MAX_MMR = 10000

TEAMS_FILE = "teams.csv"
TEAMS_AMOUNT = 100
MIN_YEAR_TEAM = 2005
MAX_YEAR_TEAM = 2021
MAX_DURATION = 30
MIN_EARNINGS = 1e3
MAX_EARNINGS = 1e7

TOURNAMENTS_FILE = "tournaments.csv"
TOURNAMENTS_AMOUNT = 15
MIN_PRIZE = 1e5
MAX_PRIZE = 4e7
MIN_YEAR_EVENT = 2005
MAX_YEAR_EVENT = 2021

COMPANIES_FILE = "companies.csv"
COMPANIES_AMOUNT = 50
MIN_REVENUE = 1e3
MAX_REVENUE = 1e6

TEAM_PLAYER_FILE = "teams_players.csv"
PLAYERS_PER_TEAM = 5

COMPANIES_TOURNAMENTS_FILE = "companies_tournaments.csv"
MIN_SPONSORS = 5
MAX_SPONSORS = 50
MIN_DEPOSIT = 1e4
MAX_DEPOSIT = 1e6

COMPANIES_TEAMS_FILE = "companies_teams.csv"

TOURNAMENTS_TEAMS_FILE = "tournaments_teams.csv"

MATCHES_FILE = "matches.csv"
MIN_MATCH_DURATION = 20
MAX_MATCH_DURATION = 80

MATCHES_PERFOMANCES_FILE = "match_perfomances.csv"
MIN_KDA = 0
MAX_KDA = 30
MIN_NETWORTH = 10000
MAX_NETWORTH = 40000
MIN_LH = 0
MAX_LH = 500
MIN_DN = 0
MAX_DN = 50
MIN_GPM = 200
MAX_GPM = 1000
MIN_XPM = 300
MAX_XPM = 1200
MIN_DMG = 1000
MAX_DMG = 100000
MIN_HEAL = 0
MAX_HEAL = 20000
MIN_BLD = 0
MAX_BLD = 20000


COUNTRIES_FILE = "./txt/countries.txt"
HEROES_FILE = "./txt/heroes_list.txt"
ROLES_FILE = "./txt/roles.txt"
CITIES_FILE = "./txt/cities.txt"
REGIONS_FILE = "./txt/regions.txt"

MIN_TIER = 1
MAX_TIER = 4
